version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/docker-airflow/
hooks:
#  ApplicationStop:
#    - location: script/applicationstop.sh
#      timeout: 20
#      runas: ec2-user
  ApplicationStart:
    - location: script/applicationstart.sh
      timeout: 300
      runas: ec2-user