version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/docker-airflow/
hooks:
  ApplicationStart:
    - location: script/applicationstart.sh
      timeout: 300
      runas: ec2-user